[workspace]
members = [
    "parent",
    "core",
    "encoding",
    "parser",
    "transfer-syntax-registry",
    "object",
    "dictionary-std",
    "dictionary-builder",
    "dcmdump",
    "ul",
    "scpproxy"
]
