[package]
name = "scpproxy"
version = "0.1.0"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>", "Paul Knopf <pauldotknopf@gmail.com>"]
description = "A proxy SCP server, for logging and diagnostics"
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"

[dependencies]
clap = "2.33.0"
quick-error = "1.2.3"
dicom-ul = { path = "../ul/", version = "0.1.0" }
dicom-dictionary-std = { path = "../dictionary-std/", version = "0.1.0" }
