[package]
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "Efficient and practical base library for DICOM compliant systems"
name = "dicom-core"
publish = false
license = "MIT/Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
version = "0.1.0-pre.1"
edition = "2018"

[badges]

[badges.travis-ci]
repository = "Enet4/dicom-rs"

[dependencies]
chrono = "0.4.6"
itertools = "0.8.0"
quick-error = "1.2.2"
smallvec = "0.6.7"
