[package]
name = "dicom-parser"
version = "0.2.0"
authors = ["Eduardo Pinho <enet4mikeenet@gmail.com>"]
description = "A middle-level parser and printer of DICOM data sets"
edition = "2018"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Enet4/dicom-rs"
categories = ["parser-implementations"]
keywords = ["dicom", "parser"]
readme = "README.md"

[badges.travis-ci]
repository = "Enet4/dicom-rs"

[dependencies]
dicom-core = { path = "../core", version = "0.2.0" }
dicom-encoding = { path = "../encoding", version = "0.2.0" }
quick-error = "1.2.3"
chrono = "0.4.6"
dicom-dictionary-std = { path = "../dictionary-std/", version = "0.2.0" }
smallvec = "1.0.0"
snafu = "0.6.8"
